/* The following code was generated by JFlex 1.4.3 on 01/12/10 18:36 */

package ava.analyseurs;       


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 01/12/10 18:36 from the specification file
 * <tt>/home/tarik/Bureau/tp5/spec/anLexAva.lex</tt>
 */
public class ScannerAva implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\24\1\3\1\2\1\0\1\3\1\1\16\24\4\0\1\3\1\0"+
    "\1\4\1\0\1\23\1\44\2\0\1\35\1\36\1\30\1\26\1\43"+
    "\1\6\1\0\1\27\12\25\1\32\1\34\1\45\1\33\1\46\2\0"+
    "\32\23\1\0\1\5\2\0\1\23\1\0\1\13\1\20\1\23\1\31"+
    "\1\22\1\37\1\12\1\40\1\15\2\23\1\21\1\14\1\16\1\11"+
    "\1\7\1\23\1\10\1\41\1\17\1\47\1\23\1\42\3\23\4\0"+
    "\41\24\2\0\4\23\4\0\1\23\2\0\1\24\7\0\1\23\4\0"+
    "\1\23\5\0\27\23\1\0\37\23\1\0\u013f\23\31\0\162\23\4\0"+
    "\14\23\16\0\5\23\11\0\1\23\21\0\130\24\5\0\23\24\12\0"+
    "\1\23\13\0\1\23\1\0\3\23\1\0\1\23\1\0\24\23\1\0"+
    "\54\23\1\0\46\23\1\0\5\23\4\0\202\23\1\0\4\24\3\0"+
    "\105\23\1\0\46\23\2\0\2\23\6\0\20\23\41\0\46\23\2\0"+
    "\1\23\7\0\47\23\11\0\21\24\1\0\27\24\1\0\3\24\1\0"+
    "\1\24\1\0\2\24\1\0\1\24\13\0\33\23\5\0\3\23\15\0"+
    "\4\24\14\0\6\24\13\0\32\23\5\0\13\23\16\24\7\0\12\25"+
    "\4\0\2\23\1\24\143\23\1\0\1\23\10\24\1\0\6\24\2\23"+
    "\2\24\1\0\4\24\2\23\12\25\3\23\2\0\1\23\17\0\1\24"+
    "\1\23\1\24\36\23\33\24\2\0\3\23\60\0\46\23\13\24\1\23"+
    "\u014f\0\3\24\66\23\2\0\1\24\1\23\20\24\2\0\1\23\4\24"+
    "\3\0\12\23\2\24\2\0\12\25\21\0\3\24\1\0\10\23\2\0"+
    "\2\23\2\0\26\23\1\0\7\23\1\0\1\23\3\0\4\23\2\0"+
    "\1\24\1\23\7\24\2\0\2\24\2\0\3\24\11\0\1\24\4\0"+
    "\2\23\1\0\3\23\2\24\2\0\12\25\4\23\15\0\3\24\1\0"+
    "\6\23\4\0\2\23\2\0\26\23\1\0\7\23\1\0\2\23\1\0"+
    "\2\23\1\0\2\23\2\0\1\24\1\0\5\24\4\0\2\24\2\0"+
    "\3\24\13\0\4\23\1\0\1\23\7\0\12\25\2\24\3\23\14\0"+
    "\3\24\1\0\11\23\1\0\3\23\1\0\26\23\1\0\7\23\1\0"+
    "\2\23\1\0\5\23\2\0\1\24\1\23\10\24\1\0\3\24\1\0"+
    "\3\24\2\0\1\23\17\0\2\23\2\24\2\0\12\25\1\0\1\23"+
    "\17\0\3\24\1\0\10\23\2\0\2\23\2\0\26\23\1\0\7\23"+
    "\1\0\2\23\1\0\5\23\2\0\1\24\1\23\6\24\3\0\2\24"+
    "\2\0\3\24\10\0\2\24\4\0\2\23\1\0\3\23\4\0\12\25"+
    "\1\0\1\23\20\0\1\24\1\23\1\0\6\23\3\0\3\23\1\0"+
    "\4\23\3\0\2\23\1\0\1\23\1\0\2\23\3\0\2\23\3\0"+
    "\3\23\3\0\10\23\1\0\3\23\4\0\5\24\3\0\3\24\1\0"+
    "\4\24\11\0\1\24\17\0\11\25\11\0\1\23\7\0\3\24\1\0"+
    "\10\23\1\0\3\23\1\0\27\23\1\0\12\23\1\0\5\23\4\0"+
    "\7\24\1\0\3\24\1\0\4\24\7\0\2\24\11\0\2\23\4\0"+
    "\12\25\22\0\2\24\1\0\10\23\1\0\3\23\1\0\27\23\1\0"+
    "\12\23\1\0\5\23\2\0\1\24\1\23\7\24\1\0\3\24\1\0"+
    "\4\24\7\0\2\24\7\0\1\23\1\0\2\23\4\0\12\25\22\0"+
    "\2\24\1\0\10\23\1\0\3\23\1\0\27\23\1\0\20\23\4\0"+
    "\6\24\2\0\3\24\1\0\4\24\11\0\1\24\10\0\2\23\4\0"+
    "\12\25\22\0\2\24\1\0\22\23\3\0\30\23\1\0\11\23\1\0"+
    "\1\23\2\0\7\23\3\0\1\24\4\0\6\24\1\0\1\24\1\0"+
    "\10\24\22\0\2\24\15\0\60\23\1\24\2\23\7\24\4\0\10\23"+
    "\10\24\1\0\12\25\47\0\2\23\1\0\1\23\2\0\2\23\1\0"+
    "\1\23\2\0\1\23\6\0\4\23\1\0\7\23\1\0\3\23\1\0"+
    "\1\23\1\0\1\23\2\0\2\23\1\0\4\23\1\24\2\23\6\24"+
    "\1\0\2\24\1\23\2\0\5\23\1\0\1\23\1\0\6\24\2\0"+
    "\12\25\2\0\2\23\42\0\1\23\27\0\2\24\6\0\12\25\13\0"+
    "\1\24\1\0\1\24\1\0\1\24\4\0\2\24\10\23\1\0\42\23"+
    "\6\0\24\24\1\0\2\24\4\23\4\0\10\24\1\0\44\24\11\0"+
    "\1\24\71\0\42\23\1\0\5\23\1\0\2\23\1\0\7\24\3\0"+
    "\4\24\6\0\12\25\6\0\6\23\4\24\106\0\46\23\12\0\51\23"+
    "\7\0\132\23\5\0\104\23\5\0\122\23\6\0\7\23\1\0\77\23"+
    "\1\0\1\23\1\0\4\23\2\0\7\23\1\0\1\23\1\0\4\23"+
    "\2\0\47\23\1\0\1\23\1\0\4\23\2\0\37\23\1\0\1\23"+
    "\1\0\4\23\2\0\7\23\1\0\1\23\1\0\4\23\2\0\7\23"+
    "\1\0\7\23\1\0\27\23\1\0\37\23\1\0\1\23\1\0\4\23"+
    "\2\0\7\23\1\0\47\23\1\0\23\23\16\0\11\25\56\0\125\23"+
    "\14\0\u026c\23\2\0\10\23\12\0\32\23\5\0\113\23\3\0\3\23"+
    "\17\0\15\23\1\0\4\23\3\24\13\0\22\23\3\24\13\0\22\23"+
    "\2\24\14\0\15\23\1\0\3\23\1\0\2\24\14\0\64\23\40\24"+
    "\3\0\1\23\3\0\2\23\1\24\2\0\12\25\41\0\3\24\2\0"+
    "\12\25\6\0\130\23\10\0\51\23\1\24\126\0\35\23\3\0\14\24"+
    "\4\0\14\24\12\0\12\25\36\23\2\0\5\23\u038b\0\154\23\224\0"+
    "\234\23\4\0\132\23\6\0\26\23\2\0\6\23\2\0\46\23\2\0"+
    "\6\23\2\0\10\23\1\0\1\23\1\0\1\23\1\0\1\23\1\0"+
    "\37\23\2\0\65\23\1\0\7\23\1\0\1\23\3\0\3\23\1\0"+
    "\7\23\3\0\4\23\2\0\6\23\4\0\15\23\5\0\3\23\1\0"+
    "\7\23\17\0\4\24\32\0\5\24\20\0\2\23\23\0\1\23\13\0"+
    "\4\24\6\0\6\24\1\0\1\23\15\0\1\23\40\0\22\23\36\0"+
    "\15\24\4\0\1\24\3\0\6\24\27\0\1\23\4\0\1\23\2\0"+
    "\12\23\1\0\1\23\3\0\5\23\6\0\1\23\1\0\1\23\1\0"+
    "\1\23\1\0\4\23\1\0\3\23\1\0\7\23\3\0\3\23\5\0"+
    "\5\23\26\0\44\23\u0e81\0\3\23\31\0\11\23\6\24\1\0\5\23"+
    "\2\0\5\23\4\0\126\23\2\0\2\24\2\0\3\23\1\0\137\23"+
    "\5\0\50\23\4\0\136\23\21\0\30\23\70\0\20\23\u0200\0\u19b6\23"+
    "\112\0\u51a6\23\132\0\u048d\23\u0773\0\u2ba4\23\u215c\0\u012e\23\2\0\73\23"+
    "\225\0\7\23\14\0\5\23\5\0\1\23\1\24\12\23\1\0\15\23"+
    "\1\0\5\23\1\0\1\23\1\0\2\23\1\0\2\23\1\0\154\23"+
    "\41\0\u016b\23\22\0\100\23\2\0\66\23\50\0\15\23\3\0\20\24"+
    "\20\0\4\24\17\0\2\23\30\0\3\23\31\0\1\23\6\0\5\23"+
    "\1\0\207\23\2\0\1\24\4\0\1\23\13\0\12\25\7\0\32\23"+
    "\4\0\1\23\1\0\32\23\12\0\132\23\3\0\6\23\2\0\6\23"+
    "\2\0\6\23\2\0\3\23\3\0\2\23\3\0\2\23\22\0\3\24"+
    "\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\14\4\1\5\1\6"+
    "\1\7\1\10\1\1\1\11\1\12\1\13\1\14\2\4"+
    "\1\15\1\1\1\16\1\17\1\0\1\20\2\0\2\4"+
    "\1\21\3\4\1\22\7\4\1\23\1\24\3\4\1\25"+
    "\1\26\1\27\1\30\1\31\1\20\2\32\2\4\1\33"+
    "\1\34\1\35\1\36\12\4\1\37\1\40\1\41\1\4"+
    "\1\42\1\0\1\43\5\4\2\0\1\44\1\45\1\46"+
    "\2\4\1\47\1\0\1\4\1\50\1\51\1\0\1\52"+
    "\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\50\0\170\0\240\0\310\0\360"+
    "\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230"+
    "\0\u0258\0\u0280\0\u02a8\0\50\0\u02d0\0\50\0\u02f8\0\50"+
    "\0\50\0\50\0\50\0\u0320\0\u0348\0\50\0\u0370\0\u0398"+
    "\0\u03c0\0\170\0\50\0\u03e8\0\u0410\0\u0438\0\u0460\0\u0140"+
    "\0\u0488\0\u04b0\0\u04d8\0\u0140\0\u0500\0\u0528\0\u0550\0\u0578"+
    "\0\u05a0\0\u05c8\0\u05f0\0\50\0\50\0\u0618\0\u0640\0\u0668"+
    "\0\50\0\50\0\50\0\50\0\50\0\170\0\u0690\0\50"+
    "\0\u06b8\0\u06e0\0\u0140\0\u0140\0\u0140\0\u0140\0\u0708\0\u0730"+
    "\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820\0\u0848\0\u0870"+
    "\0\u0140\0\u0140\0\u0140\0\u0898\0\u0140\0\u08c0\0\u0140\0\u08e8"+
    "\0\u0910\0\u0938\0\u0960\0\u0988\0\u09b0\0\u09d8\0\u0140\0\u0a00"+
    "\0\u0140\0\u0a28\0\u0a50\0\50\0\u0a78\0\u0aa0\0\u0140\0\u0140"+
    "\0\u0ac8\0\u0140\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\12\1\2\1\23\1\24\1\25\1\26"+
    "\1\12\1\27\1\30\1\31\1\32\1\33\1\34\2\12"+
    "\1\35\1\36\1\37\1\40\1\41\1\12\52\0\1\4"+
    "\45\0\2\42\1\0\1\42\1\43\1\44\42\42\6\0"+
    "\1\45\50\0\1\12\1\46\15\12\3\0\1\12\5\0"+
    "\4\12\4\0\1\12\7\0\13\12\1\47\3\12\3\0"+
    "\1\12\5\0\4\12\4\0\1\12\7\0\1\12\1\50"+
    "\15\12\3\0\1\12\5\0\4\12\4\0\1\12\7\0"+
    "\17\12\3\0\1\12\5\0\4\12\4\0\1\12\7\0"+
    "\7\12\1\51\7\12\3\0\1\12\5\0\4\12\4\0"+
    "\1\12\7\0\2\12\1\52\14\12\3\0\1\12\5\0"+
    "\4\12\4\0\1\12\7\0\7\12\1\53\7\12\3\0"+
    "\1\12\5\0\1\54\3\12\4\0\1\12\7\0\2\12"+
    "\1\55\14\12\3\0\1\12\5\0\4\12\4\0\1\12"+
    "\7\0\1\12\1\56\15\12\3\0\1\12\5\0\1\12"+
    "\1\57\2\12\4\0\1\12\7\0\2\12\1\60\14\12"+
    "\3\0\1\12\5\0\4\12\4\0\1\12\7\0\2\12"+
    "\1\61\14\12\3\0\1\12\5\0\4\12\4\0\1\12"+
    "\7\0\7\12\1\62\2\12\1\63\4\12\3\0\1\12"+
    "\5\0\4\12\4\0\1\12\25\0\1\23\55\0\1\64"+
    "\47\0\1\65\23\0\4\12\1\66\12\12\3\0\1\12"+
    "\5\0\4\12\4\0\1\12\7\0\1\12\1\67\15\12"+
    "\3\0\1\12\5\0\1\12\1\70\2\12\4\0\1\12"+
    "\15\0\1\71\2\0\1\72\20\0\1\73\41\0\1\74"+
    "\47\0\1\75\14\0\2\42\1\0\1\42\1\76\1\44"+
    "\42\42\1\45\1\77\1\100\45\45\7\0\2\12\1\101"+
    "\14\12\3\0\1\12\5\0\4\12\4\0\1\12\7\0"+
    "\4\12\1\102\12\12\3\0\1\12\5\0\4\12\4\0"+
    "\1\12\7\0\17\12\3\0\1\103\5\0\4\12\4\0"+
    "\1\12\7\0\17\12\3\0\1\104\5\0\4\12\4\0"+
    "\1\12\7\0\10\12\1\105\6\12\3\0\1\12\5\0"+
    "\4\12\4\0\1\12\7\0\10\12\1\106\6\12\3\0"+
    "\1\12\5\0\4\12\4\0\1\12\7\0\17\12\3\0"+
    "\1\12\5\0\4\12\4\0\1\107\7\0\13\12\1\110"+
    "\3\12\3\0\1\12\5\0\4\12\4\0\1\12\7\0"+
    "\2\12\1\111\14\12\3\0\1\12\5\0\4\12\4\0"+
    "\1\12\7\0\2\12\1\112\14\12\3\0\1\12\5\0"+
    "\4\12\4\0\1\12\7\0\17\12\3\0\1\113\5\0"+
    "\4\12\4\0\1\12\7\0\17\12\3\0\1\12\5\0"+
    "\2\12\1\114\1\12\4\0\1\12\7\0\12\12\1\115"+
    "\4\12\3\0\1\12\5\0\4\12\4\0\1\12\7\0"+
    "\6\12\1\116\10\12\3\0\1\12\5\0\4\12\4\0"+
    "\1\12\7\0\6\12\1\117\10\12\3\0\1\12\5\0"+
    "\4\12\4\0\1\12\2\0\1\100\54\0\3\12\1\120"+
    "\13\12\3\0\1\12\5\0\4\12\4\0\1\12\7\0"+
    "\17\12\3\0\1\121\5\0\4\12\4\0\1\12\7\0"+
    "\13\12\1\122\3\12\3\0\1\12\5\0\4\12\4\0"+
    "\1\12\7\0\7\12\1\123\7\12\3\0\1\12\5\0"+
    "\4\12\4\0\1\12\7\0\12\12\1\124\4\12\3\0"+
    "\1\12\5\0\4\12\4\0\1\12\7\0\1\125\16\12"+
    "\3\0\1\12\5\0\4\12\4\0\1\12\1\0\3\126"+
    "\3\0\17\12\3\0\1\12\5\0\4\12\4\0\1\12"+
    "\7\0\13\12\1\127\3\12\3\0\1\12\5\0\4\12"+
    "\4\0\1\12\7\0\17\12\3\0\1\12\5\0\2\12"+
    "\1\130\1\12\4\0\1\12\7\0\10\12\1\131\6\12"+
    "\3\0\1\12\5\0\4\12\4\0\1\12\7\0\12\12"+
    "\1\132\4\12\3\0\1\12\5\0\4\12\4\0\1\12"+
    "\7\0\1\12\1\133\15\12\3\0\1\12\5\0\4\12"+
    "\4\0\1\12\7\0\13\12\1\134\3\12\3\0\1\12"+
    "\5\0\4\12\4\0\1\12\1\0\3\126\11\0\1\135"+
    "\3\0\1\136\35\0\13\12\1\137\3\12\3\0\1\12"+
    "\5\0\4\12\4\0\1\12\7\0\13\12\1\140\3\12"+
    "\3\0\1\12\5\0\4\12\4\0\1\12\7\0\13\12"+
    "\1\141\3\12\3\0\1\12\5\0\4\12\4\0\1\12"+
    "\7\0\4\12\1\142\12\12\3\0\1\12\5\0\4\12"+
    "\4\0\1\12\7\0\4\12\1\143\12\12\3\0\1\12"+
    "\5\0\4\12\4\0\1\12\37\0\1\144\21\0\1\145"+
    "\45\0\12\12\1\146\4\12\3\0\1\12\5\0\4\12"+
    "\4\0\1\12\7\0\5\12\1\147\11\12\3\0\1\12"+
    "\5\0\4\12\4\0\1\12\7\0\7\12\1\150\7\12"+
    "\3\0\1\12\5\0\4\12\4\0\1\12\11\0\1\151"+
    "\45\0\7\12\1\152\7\12\3\0\1\12\5\0\4\12"+
    "\4\0\1\12\7\0\1\153\40\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\17\1\1\11\1\1\1\11"+
    "\1\1\4\11\2\1\1\11\3\1\1\0\1\11\2\0"+
    "\16\1\2\11\3\1\5\11\2\1\1\11\25\1\1\0"+
    "\6\1\2\0\5\1\1\11\1\0\3\1\1\0\1\1"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
private Symbole creerSymbole(String s, int t) {
    return new Symbole(s,t,yyline,yycolumn);
  }
private Symbole creerSymbole(String s, int t, Object v) {
    return new Symbole(s,t,v,yyline,yycolumn);
  }  


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScannerAva(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ScannerAva(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1742) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, ScannerException
 {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { // on a reconnu un format pour impression de chaine
  return creerSymbole("FORMATC",TypeSymboles.FORMATC);
          }
        case 44: break;
        case 16: 
          { // on a reconnu une chaine
  return creerSymbole("CHAINE",TypeSymboles.CHAINE,yytext().substring(1,yylength() - 1));
          }
        case 45: break;
        case 10: 
          { // on a reconnu un ";"
  return creerSymbole("FININSTR",TypeSymboles.FININSTR);
          }
        case 46: break;
        case 38: 
          { // on a reconnu un while
  return creerSymbole("WHILE",TypeSymboles.WHILE);
          }
        case 47: break;
        case 28: 
          { // on a reconnu un op�rateur MOD
  return creerSymbole("MOD",TypeSymboles.MOD);
          }
        case 48: break;
        case 31: 
          { // on a reconnu un read
  return creerSymbole("READ",TypeSymboles.READ);
          }
        case 49: break;
        case 15: 
          { // on a reconnu un comparateur pour sup�rieur strict
  return creerSymbole("SUP",TypeSymboles.SUP);
          }
        case 50: break;
        case 11: 
          { // on a reconnu un "("
  return creerSymbole("PARO",TypeSymboles.PARO);
          }
        case 51: break;
        case 7: 
          { // on a reconnu un op�rateur DIV
  return creerSymbole("DIV",TypeSymboles.DIV);
          }
        case 52: break;
        case 13: 
          { // on a reconnu un ","
  return creerSymbole("SEP",TypeSymboles.SEP);
          }
        case 53: break;
        case 9: 
          { // on a reconnu un comparateur pour �galit�
  return creerSymbole("EGAL",TypeSymboles.EGAL);
          }
        case 54: break;
        case 29: 
          { // on a reconnu le mot-cl� int
  return creerSymbole("DECLINT",TypeSymboles.DECLINT);
          }
        case 55: break;
        case 37: 
          { // on a reconnu un write
  return creerSymbole("WRITE",TypeSymboles.WRITE);
          }
        case 56: break;
        case 34: 
          { // on a reconnu un loop
  return creerSymbole("DO",TypeSymboles.LOOP);
          }
        case 57: break;
        case 19: 
          { // on a reconnu un comparateur pour diff�rence
  return creerSymbole("DIFF",TypeSymboles.DIFF);
          }
        case 58: break;
        case 36: 
          { return creerSymbole("FALSE",TypeSymboles.FALSE);
          }
        case 59: break;
        case 18: 
          { // on a reconnu un if
  return creerSymbole("IF",TypeSymboles.IF);
          }
        case 60: break;
        case 20: 
          { // on a reconnu un op�rateur d'affectation
  return creerSymbole("AFFECT",TypeSymboles.AFFECT);
          }
        case 61: break;
        case 2: 
          { /* on ignore les blancs */
          }
        case 62: break;
        case 43: 
          { // on a reconnu un end loop
  return creerSymbole("DONE",TypeSymboles.DONE);
          }
        case 63: break;
        case 42: 
          { // on a reconnu un writeln
  return creerSymbole("WRITELN",TypeSymboles.WRITELN);
          }
        case 64: break;
        case 32: 
          { return creerSymbole("TRUE",TypeSymboles.TRUE);
          }
        case 65: break;
        case 8: 
          { // on a reconnu un op�rateur MULT
  return creerSymbole("MULT",TypeSymboles.MULT);
          }
        case 66: break;
        case 1: 
          { // erreur
  throw new ScannerException("token inconnu, caract�re " + yytext() + 
				 " ligne " + yyline + " colonne " + yycolumn);
          }
        case 67: break;
        case 22: 
          { // on a reconnu un format pour impression de booleen
  return creerSymbole("FORMATB",TypeSymboles.FORMATB);
          }
        case 68: break;
        case 21: 
          { // on a reconnu un format pour impression d'entier
  return creerSymbole("FORMATI",TypeSymboles.FORMATI);
          }
        case 69: break;
        case 5: 
          { // on a reconnu un entier
  return creerSymbole("ENTIER",TypeSymboles.ENTIER,new Integer(yytext()));
          }
        case 70: break;
        case 30: 
          { // on a reconnu un not
  return creerSymbole("NOT",TypeSymboles.NOT);
          }
        case 71: break;
        case 4: 
          { // on a reconnu un identificateur
  return creerSymbole("IDENT",TypeSymboles.IDENT,yytext());
          }
        case 72: break;
        case 12: 
          { // on a reconnu un ")"
  return creerSymbole("PARF",TypeSymboles.PARF);
          }
        case 73: break;
        case 17: 
          { // on a reconnu un or
  return creerSymbole("OR",TypeSymboles.OR);
          }
        case 74: break;
        case 24: 
          { // on a reconnu un comparateur pour inf�rieur ou �gal
  return creerSymbole("INFEGAL",TypeSymboles.INFEGAL);
          }
        case 75: break;
        case 6: 
          { // on a reconnu un op�rateur plus
  return creerSymbole("PLUS",TypeSymboles.PLUS);
          }
        case 76: break;
        case 33: 
          { // on a reconnu un then
  return creerSymbole("THEN",TypeSymboles.THEN);
          }
        case 77: break;
        case 40: 
          { // on a reconnu le mot-cl� program
  return creerSymbole("PROG",TypeSymboles.PROG);
          }
        case 78: break;
        case 25: 
          { // on a reconnu un comparateur pour sup�rieur ou �gal
  return creerSymbole("SUPEGAL",TypeSymboles.SUPEGAL);
          }
        case 79: break;
        case 26: 
          { /* on ignore les commentaires */
          }
        case 80: break;
        case 35: 
          { // on a reconnu un else
  return creerSymbole("ELSE",TypeSymboles.ELSE);
          }
        case 81: break;
        case 41: 
          { // on a reconnu le mot-cl� boolean
  return creerSymbole("DECLBOOL",TypeSymboles.DECLBOOL);
          }
        case 82: break;
        case 39: 
          { // on a reconnu un end if
  return creerSymbole("FI",TypeSymboles.FI);
          }
        case 83: break;
        case 27: 
          { // on a reconnu un and
  return creerSymbole("AND",TypeSymboles.AND);
          }
        case 84: break;
        case 3: 
          { // on a reconnu un op�rateur moins
  return creerSymbole("MOINS",TypeSymboles.MOINS);
          }
        case 85: break;
        case 14: 
          { // on a reconnu un comparateur pour inf�rieur strict
  return creerSymbole("INF",TypeSymboles.INF);
          }
        case 86: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {   return new Symbole(TypeSymboles.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
