
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 27 10:36:35 CEST 2010
//----------------------------------------------------

package init.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int READ = 4;
  public static final int IDENT = 6;
  public static final int SEPVAR = 11;
  public static final int FINLISTE = 13;
  public static final int PROG = 2;
  public static final int EOF = 0;
  public static final int DEBLISTE = 12;
  public static final int DECLINT = 3;
  public static final int FININSTR = 9;
  public static final int DECLLIST = 5;
  public static final int ENTIER = 7;
  public static final int error = 1;
  public static final int AFF = 8;
  public static final int VIRG = 10;
}

