
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 13 18:07:11 CEST 2010
//----------------------------------------------------

package ava.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int OPENPARENTH = 27;
  public static final int FININSTR = 11;
  public static final int MULT = 31;
  public static final int EGAL = 39;
  public static final int ENDLOOP = 25;
  public static final int FORMATENTIER = 14;
  public static final int WRITE = 5;
  public static final int SUPEGAL = 38;
  public static final int UNAIRE = 33;
  public static final int FORMATCHAINE = 16;
  public static final int AND = 41;
  public static final int NOT = 40;
  public static final int OR = 42;
  public static final int INF = 36;
  public static final int INFEGAL = 35;
  public static final int DIV = 32;
  public static final int LOOP = 24;
  public static final int PLUS = 30;
  public static final int IF = 19;
  public static final int WRITELN = 6;
  public static final int EOF = 0;
  public static final int GUILLEMET = 13;
  public static final int error = 1;
  public static final int FAUX = 44;
  public static final int MODULO = 26;
  public static final int MOINS = 29;
  public static final int IDENT = 8;
  public static final int DECLBOOL = 4;
  public static final int ENDIF = 22;
  public static final int CANCEL = 18;
  public static final int ELSE = 21;
  public static final int READ = 7;
  public static final int SEPVAR = 12;
  public static final int WHILE = 23;
  public static final int SUP = 37;
  public static final int THEN = 20;
  public static final int PROG = 2;
  public static final int VRAI = 43;
  public static final int DECLINT = 3;
  public static final int STRING = 17;
  public static final int DIFF = 34;
  public static final int CLOSEPARENTH = 28;
  public static final int FORMATBOOLEEN = 15;
  public static final int ENTIER = 9;
  public static final int AFF = 10;
}

