/* The following code was generated by JFlex 1.4.1 on 02/12/10 16:30 */

/*****************************************************
 * Analyseur lexical pour Ava version simple
 * fichier de description pour JFlex
 * produit anLexAva/ScannerAva.java
 * F. Bellano
 * 07/10/10
 ****************************************************/

/***********************************************************************
 * Première partie : code utilisateur inclus tel quel dans le fichier
 * .java généré. On met typiquement ici les déclarations de paquetage
 * (package) et les importations de classes (import).
 ***********************************************************************/

// déclaration du paquetage auquel appartient la classe générée
package ava.analyseurs;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 02/12/10 16:30 from the specification file
 * <tt>/home/l3/bellano/Bureau/COO/COMPIL-TP6/spec/anLexAva.lex</tt>
 */
public class ScannerAva implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\13\1\3\1\2\1\0\1\3\1\1\16\13\4\0\1\3\1\0"+
    "\1\20\1\0\1\12\1\47\2\0\1\45\1\46\1\44\1\43\1\37"+
    "\1\17\1\0\1\40\12\14\1\15\1\36\1\41\1\16\1\42\2\0"+
    "\32\12\1\0\1\21\2\0\1\12\1\0\1\10\1\31\1\12\1\24"+
    "\1\22\1\27\1\7\1\33\1\26\2\12\1\25\1\11\1\23\1\6"+
    "\1\4\1\12\1\5\1\34\1\30\1\35\1\12\1\32\3\12\4\0"+
    "\41\13\2\0\4\12\4\0\1\12\2\0\1\13\7\0\1\12\4\0"+
    "\1\12\5\0\27\12\1\0\37\12\1\0\u013f\12\31\0\162\12\4\0"+
    "\14\12\16\0\5\12\11\0\1\12\21\0\130\13\5\0\23\13\12\0"+
    "\1\12\13\0\1\12\1\0\3\12\1\0\1\12\1\0\24\12\1\0"+
    "\54\12\1\0\46\12\1\0\5\12\4\0\202\12\1\0\4\13\3\0"+
    "\105\12\1\0\46\12\2\0\2\12\6\0\20\12\41\0\46\12\2\0"+
    "\1\12\7\0\47\12\11\0\21\13\1\0\27\13\1\0\3\13\1\0"+
    "\1\13\1\0\2\13\1\0\1\13\13\0\33\12\5\0\3\12\15\0"+
    "\4\13\14\0\6\13\13\0\32\12\5\0\13\12\16\13\7\0\12\14"+
    "\4\0\2\12\1\13\143\12\1\0\1\12\10\13\1\0\6\13\2\12"+
    "\2\13\1\0\4\13\2\12\12\14\3\12\2\0\1\12\17\0\1\13"+
    "\1\12\1\13\36\12\33\13\2\0\3\12\60\0\46\12\13\13\1\12"+
    "\u014f\0\3\13\66\12\2\0\1\13\1\12\20\13\2\0\1\12\4\13"+
    "\3\0\12\12\2\13\2\0\12\14\21\0\3\13\1\0\10\12\2\0"+
    "\2\12\2\0\26\12\1\0\7\12\1\0\1\12\3\0\4\12\2\0"+
    "\1\13\1\12\7\13\2\0\2\13\2\0\3\13\11\0\1\13\4\0"+
    "\2\12\1\0\3\12\2\13\2\0\12\14\4\12\15\0\3\13\1\0"+
    "\6\12\4\0\2\12\2\0\26\12\1\0\7\12\1\0\2\12\1\0"+
    "\2\12\1\0\2\12\2\0\1\13\1\0\5\13\4\0\2\13\2\0"+
    "\3\13\13\0\4\12\1\0\1\12\7\0\12\14\2\13\3\12\14\0"+
    "\3\13\1\0\11\12\1\0\3\12\1\0\26\12\1\0\7\12\1\0"+
    "\2\12\1\0\5\12\2\0\1\13\1\12\10\13\1\0\3\13\1\0"+
    "\3\13\2\0\1\12\17\0\2\12\2\13\2\0\12\14\1\0\1\12"+
    "\17\0\3\13\1\0\10\12\2\0\2\12\2\0\26\12\1\0\7\12"+
    "\1\0\2\12\1\0\5\12\2\0\1\13\1\12\6\13\3\0\2\13"+
    "\2\0\3\13\10\0\2\13\4\0\2\12\1\0\3\12\4\0\12\14"+
    "\1\0\1\12\20\0\1\13\1\12\1\0\6\12\3\0\3\12\1\0"+
    "\4\12\3\0\2\12\1\0\1\12\1\0\2\12\3\0\2\12\3\0"+
    "\3\12\3\0\10\12\1\0\3\12\4\0\5\13\3\0\3\13\1\0"+
    "\4\13\11\0\1\13\17\0\11\14\11\0\1\12\7\0\3\13\1\0"+
    "\10\12\1\0\3\12\1\0\27\12\1\0\12\12\1\0\5\12\4\0"+
    "\7\13\1\0\3\13\1\0\4\13\7\0\2\13\11\0\2\12\4\0"+
    "\12\14\22\0\2\13\1\0\10\12\1\0\3\12\1\0\27\12\1\0"+
    "\12\12\1\0\5\12\2\0\1\13\1\12\7\13\1\0\3\13\1\0"+
    "\4\13\7\0\2\13\7\0\1\12\1\0\2\12\4\0\12\14\22\0"+
    "\2\13\1\0\10\12\1\0\3\12\1\0\27\12\1\0\20\12\4\0"+
    "\6\13\2\0\3\13\1\0\4\13\11\0\1\13\10\0\2\12\4\0"+
    "\12\14\22\0\2\13\1\0\22\12\3\0\30\12\1\0\11\12\1\0"+
    "\1\12\2\0\7\12\3\0\1\13\4\0\6\13\1\0\1\13\1\0"+
    "\10\13\22\0\2\13\15\0\60\12\1\13\2\12\7\13\4\0\10\12"+
    "\10\13\1\0\12\14\47\0\2\12\1\0\1\12\2\0\2\12\1\0"+
    "\1\12\2\0\1\12\6\0\4\12\1\0\7\12\1\0\3\12\1\0"+
    "\1\12\1\0\1\12\2\0\2\12\1\0\4\12\1\13\2\12\6\13"+
    "\1\0\2\13\1\12\2\0\5\12\1\0\1\12\1\0\6\13\2\0"+
    "\12\14\2\0\2\12\42\0\1\12\27\0\2\13\6\0\12\14\13\0"+
    "\1\13\1\0\1\13\1\0\1\13\4\0\2\13\10\12\1\0\42\12"+
    "\6\0\24\13\1\0\2\13\4\12\4\0\10\13\1\0\44\13\11\0"+
    "\1\13\71\0\42\12\1\0\5\12\1\0\2\12\1\0\7\13\3\0"+
    "\4\13\6\0\12\14\6\0\6\12\4\13\106\0\46\12\12\0\51\12"+
    "\7\0\132\12\5\0\104\12\5\0\122\12\6\0\7\12\1\0\77\12"+
    "\1\0\1\12\1\0\4\12\2\0\7\12\1\0\1\12\1\0\4\12"+
    "\2\0\47\12\1\0\1\12\1\0\4\12\2\0\37\12\1\0\1\12"+
    "\1\0\4\12\2\0\7\12\1\0\1\12\1\0\4\12\2\0\7\12"+
    "\1\0\7\12\1\0\27\12\1\0\37\12\1\0\1\12\1\0\4\12"+
    "\2\0\7\12\1\0\47\12\1\0\23\12\16\0\11\14\56\0\125\12"+
    "\14\0\u026c\12\2\0\10\12\12\0\32\12\5\0\113\12\3\0\3\12"+
    "\17\0\15\12\1\0\4\12\3\13\13\0\22\12\3\13\13\0\22\12"+
    "\2\13\14\0\15\12\1\0\3\12\1\0\2\13\14\0\64\12\40\13"+
    "\3\0\1\12\3\0\2\12\1\13\2\0\12\14\41\0\3\13\2\0"+
    "\12\14\6\0\130\12\10\0\51\12\1\13\126\0\35\12\3\0\14\13"+
    "\4\0\14\13\12\0\12\14\36\12\2\0\5\12\u038b\0\154\12\224\0"+
    "\234\12\4\0\132\12\6\0\26\12\2\0\6\12\2\0\46\12\2\0"+
    "\6\12\2\0\10\12\1\0\1\12\1\0\1\12\1\0\1\12\1\0"+
    "\37\12\2\0\65\12\1\0\7\12\1\0\1\12\3\0\3\12\1\0"+
    "\7\12\3\0\4\12\2\0\6\12\4\0\15\12\5\0\3\12\1\0"+
    "\7\12\17\0\4\13\32\0\5\13\20\0\2\12\23\0\1\12\13\0"+
    "\4\13\6\0\6\13\1\0\1\12\15\0\1\12\40\0\22\12\36\0"+
    "\15\13\4\0\1\13\3\0\6\13\27\0\1\12\4\0\1\12\2\0"+
    "\12\12\1\0\1\12\3\0\5\12\6\0\1\12\1\0\1\12\1\0"+
    "\1\12\1\0\4\12\1\0\3\12\1\0\7\12\3\0\3\12\5\0"+
    "\5\12\26\0\44\12\u0e81\0\3\12\31\0\11\12\6\13\1\0\5\12"+
    "\2\0\5\12\4\0\126\12\2\0\2\13\2\0\3\12\1\0\137\12"+
    "\5\0\50\12\4\0\136\12\21\0\30\12\70\0\20\12\u0200\0\u19b6\12"+
    "\112\0\u51a6\12\132\0\u048d\12\u0773\0\u2ba4\12\u215c\0\u012e\12\2\0\73\12"+
    "\225\0\7\12\14\0\5\12\5\0\1\12\1\13\12\12\1\0\15\12"+
    "\1\0\5\12\1\0\1\12\1\0\2\12\1\0\2\12\1\0\154\12"+
    "\41\0\u016b\12\22\0\100\12\2\0\66\12\50\0\15\12\3\0\20\13"+
    "\20\0\4\13\17\0\2\12\30\0\3\12\31\0\1\12\6\0\5\12"+
    "\1\0\207\12\2\0\1\13\4\0\1\12\13\0\12\14\7\0\32\12"+
    "\4\0\1\12\1\0\32\12\12\0\132\12\3\0\6\12\2\0\6\12"+
    "\2\0\6\12\2\0\3\12\3\0\2\12\3\0\2\12\22\0\3\13"+
    "\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\6\3\1\4\1\1\1\5\1\6"+
    "\1\1\10\3\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\1\2\3\1\20\2\3\1\21"+
    "\2\0\1\22\1\0\5\3\1\23\6\3\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\2\3\1\32\1\33\2\34"+
    "\1\22\2\3\1\35\1\3\1\36\7\3\1\37\1\0"+
    "\1\40\1\41\1\3\1\42\1\43\4\3\2\0\1\44"+
    "\1\3\1\45\1\46\1\3\1\0\1\47\2\3\1\50"+
    "\1\0\1\51\1\52\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\50\0\170\0\240\0\310\0\360"+
    "\0\u0118\0\u0140\0\u0168\0\u0190\0\50\0\u01b8\0\u01e0\0\u0208"+
    "\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\50"+
    "\0\50\0\u0348\0\u0370\0\u0398\0\50\0\50\0\50\0\50"+
    "\0\u03c0\0\u03e8\0\u0410\0\360\0\u0438\0\u0460\0\50\0\u0488"+
    "\0\u01e0\0\50\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578"+
    "\0\360\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0668\0\50"+
    "\0\50\0\50\0\50\0\50\0\50\0\u0690\0\u06b8\0\360"+
    "\0\360\0\u06e0\0\50\0\u01e0\0\u0708\0\u0730\0\360\0\u0758"+
    "\0\360\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820\0\u0848\0\u0870"+
    "\0\360\0\u0898\0\360\0\360\0\u08c0\0\360\0\360\0\u08e8"+
    "\0\u0910\0\u0938\0\u0960\0\u0988\0\u09b0\0\360\0\u09d8\0\u0a00"+
    "\0\360\0\u0a28\0\u0a50\0\50\0\u0a78\0\u0aa0\0\360\0\u0ac8"+
    "\0\360\0\360\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\10\1\2\1\13\1\14\1\15\1\16\1\17"+
    "\1\2\1\20\1\21\1\10\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\3\10\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\52\0\1\4\51\0"+
    "\1\10\1\42\7\10\5\0\14\10\16\0\11\10\5\0"+
    "\1\43\13\10\16\0\1\10\1\44\7\10\5\0\14\10"+
    "\16\0\11\10\5\0\14\10\16\0\11\10\5\0\1\10"+
    "\1\45\12\10\16\0\2\10\1\46\6\10\5\0\14\10"+
    "\26\0\1\13\51\0\1\47\50\0\1\50\30\0\1\51"+
    "\2\0\15\51\1\52\1\53\26\51\4\0\11\10\5\0"+
    "\1\10\1\54\1\10\1\55\10\10\16\0\2\10\1\56"+
    "\6\10\5\0\14\10\16\0\2\10\1\57\6\10\5\0"+
    "\14\10\16\0\11\10\5\0\1\10\1\60\3\10\1\61"+
    "\6\10\16\0\4\10\1\62\4\10\5\0\14\10\16\0"+
    "\1\10\1\63\7\10\5\0\11\10\1\64\2\10\16\0"+
    "\2\10\1\65\6\10\5\0\14\10\16\0\1\10\1\66"+
    "\7\10\5\0\11\10\1\67\2\10\30\0\1\70\47\0"+
    "\1\71\47\0\1\72\57\0\1\73\2\0\1\74\2\0"+
    "\1\75\17\0\2\10\1\76\6\10\5\0\14\10\16\0"+
    "\4\10\1\77\4\10\5\0\14\10\16\0\11\10\5\0"+
    "\2\10\1\100\11\10\16\0\11\10\5\0\2\10\1\101"+
    "\11\10\12\0\1\50\1\102\1\103\45\50\1\51\2\0"+
    "\15\51\1\104\1\53\26\51\4\0\11\10\5\0\2\10"+
    "\1\105\11\10\16\0\11\10\5\0\12\10\1\106\1\10"+
    "\16\0\11\10\5\0\6\10\1\107\5\10\16\0\2\10"+
    "\1\110\6\10\5\0\14\10\16\0\11\10\5\0\6\10"+
    "\1\111\5\10\16\0\11\10\5\0\3\10\1\112\10\10"+
    "\16\0\11\10\5\0\13\10\1\113\16\0\11\10\5\0"+
    "\1\114\13\10\16\0\2\10\1\115\6\10\5\0\14\10"+
    "\16\0\11\10\5\0\4\10\1\116\7\10\16\0\11\10"+
    "\5\0\4\10\1\117\7\10\16\0\3\10\1\120\5\10"+
    "\5\0\14\10\16\0\11\10\5\0\2\10\1\121\11\10"+
    "\14\0\1\103\46\0\3\122\11\10\5\0\14\10\16\0"+
    "\11\10\5\0\1\123\13\10\16\0\1\124\10\10\5\0"+
    "\14\10\16\0\11\10\5\0\12\10\1\125\1\10\16\0"+
    "\11\10\5\0\1\126\13\10\16\0\11\10\5\0\1\10"+
    "\1\127\12\10\16\0\11\10\5\0\3\10\1\130\10\10"+
    "\16\0\11\10\5\0\6\10\1\131\5\10\16\0\11\10"+
    "\5\0\3\10\1\132\10\10\16\0\1\10\1\133\7\10"+
    "\5\0\14\10\13\0\3\122\21\0\1\134\1\135\25\0"+
    "\11\10\5\0\1\136\13\10\16\0\11\10\5\0\1\137"+
    "\13\10\16\0\11\10\5\0\1\140\13\10\16\0\11\10"+
    "\5\0\1\141\13\10\16\0\4\10\1\142\4\10\5\0"+
    "\14\10\20\0\1\143\70\0\1\144\24\0\4\10\1\145"+
    "\4\10\5\0\14\10\16\0\11\10\5\0\3\10\1\146"+
    "\10\10\16\0\5\10\1\147\3\10\5\0\14\10\20\0"+
    "\1\150\45\0\11\10\5\0\1\10\1\151\12\10\16\0"+
    "\11\10\5\0\1\10\1\152\12\10\16\0\1\153\43\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\10\1\1\11\12\1\2\11"+
    "\3\1\4\11\6\1\1\11\2\0\1\11\1\0\14\1"+
    "\6\11\5\1\1\11\16\1\1\0\11\1\2\0\5\1"+
    "\1\0\1\11\3\1\1\0\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  private Symbole creerSymbole(String representation, int type) {
    return new Symbole(representation,type,yyline,yycolumn);
  }

  private Symbole creerSymbole(String representation, int type, Object valeur) {
    return new Symbole(representation,type,valeur,yyline,yycolumn);
  }  


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScannerAva(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ScannerAva(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1742) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, ScannerException
 {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 25: 
          { // on a reconnu un format d'impression de chaine de caracteres
return creerSymbole("FORIMPSTR",TypeSymboles.FORIMPSTR);
          }
        case 44: break;
        case 36: 
          { // on a reconnu le mot-clé "false"
   return creerSymbole("FALSE",TypeSymboles.FALSE);
          }
        case 45: break;
        case 27: 
          { // on a reconnu le mot-clé mod
  return creerSymbole("MOD",TypeSymboles.MOD);
          }
        case 46: break;
        case 4: 
          { // on a reconnu un entier, par la suite il faudra lui
	  // associer par ex sa valeur
  //return creerSymbole(TypeSymboles.ENTIER);
  return creerSymbole("ENTIER",TypeSymboles.ENTIER, new Integer(yytext()));
          }
        case 47: break;
        case 7: 
          { // on a reconnu un ";"
  return creerSymbole("FININSTR",TypeSymboles.FININSTR);
          }
        case 48: break;
        case 9: 
          { // on a reconnu un "/"
  return creerSymbole("DIV",TypeSymboles.DIV);
          }
        case 49: break;
        case 35: 
          { // on a reconnu le mot-clé "then"
  return creerSymbole("THEN",TypeSymboles.THEN);
          }
        case 50: break;
        case 5: 
          { // on a recconu un "="
  return creerSymbole("EGAL",TypeSymboles.EGAL);
          }
        case 51: break;
        case 11: 
          { // on a reconnu un ">"
  return creerSymbole("SUPS",TypeSymboles.SUPS);
          }
        case 52: break;
        case 43: 
          { // on a reconnu le mot-clé "end loop" 
  return creerSymbole("ENDLOOP",TypeSymboles.ENDLOOP);
          }
        case 53: break;
        case 31: 
          { // on a reconnu un read
  return creerSymbole("READ",TypeSymboles.READ);
          }
        case 54: break;
        case 10: 
          { // on a reconnu un "<"
  return creerSymbole("INFS",TypeSymboles.INFS);
          }
        case 55: break;
        case 39: 
          { // on a reconnu le mot-clé "end if"
  return creerSymbole("ENDIF",TypeSymboles.ENDIF);
          }
        case 56: break;
        case 1: 
          { // erreur : .|\n désigne n'importe quel caractère non reconnu
      // par une des règles précédentes 
  throw new ScannerException("symbole inconnu, caractère " + yytext() + 
				 " ligne " + yyline + " colonne " + yycolumn);
          }
        case 57: break;
        case 18: 
          { // on a reconnu une chaine de caractere
  return creerSymbole("CHAINE",TypeSymboles.CHAINE,yytext().substring(1,yylength() - 1));
          }
        case 58: break;
        case 26: 
          { // on a reconnu le mot-clé "and"
   return creerSymbole("AND",TypeSymboles.AND);
          }
        case 59: break;
        case 41: 
          { // on a reconnu le mot-clé boolean
  return creerSymbole("DECLBOOL",TypeSymboles.DECLBOOL);
          }
        case 60: break;
        case 2: 
          { /* on ignore les blancs */
          }
        case 61: break;
        case 29: 
          { // on a reconnu le mot-clé "not"
  return creerSymbole("NOT",TypeSymboles.NOT);
          }
        case 62: break;
        case 37: 
          { // on a reconnu le mot-clé write 
  return creerSymbole("WRITE",TypeSymboles.WRITE);
          }
        case 63: break;
        case 38: 
          { // on a reconnu le mot-clé "while"
  return creerSymbole("WHILE",TypeSymboles.WHILE);
          }
        case 64: break;
        case 30: 
          { // on a reconnu le mot-clé int
  return creerSymbole("DECLINT",TypeSymboles.DECLINT);
          }
        case 65: break;
        case 6: 
          { // on a reconnu un "-"
  return creerSymbole("MOINS",TypeSymboles.MOINS);
          }
        case 66: break;
        case 28: 
          { //on a reconnu un commentaire mais on fait rien
          }
        case 67: break;
        case 14: 
          { // on a reconnu un "("
  return creerSymbole("PARENTO",TypeSymboles.PARENTO);
          }
        case 68: break;
        case 8: 
          { // on a reconnu une ","
  return creerSymbole("SEPVAR",TypeSymboles.SEPVAR);
          }
        case 69: break;
        case 17: 
          { // on a reconnu un opérateur d'affectation
  return creerSymbole("AFF",TypeSymboles.AFF);
          }
        case 70: break;
        case 40: 
          { // on a reconnu le mot-clé program
  return creerSymbole("PROG",TypeSymboles.PROG);
          }
        case 71: break;
        case 24: 
          { // on a reconnu un format d'impression de booleans
return creerSymbole("FORIMPBOOL",TypeSymboles.FORIMPBOOL);
          }
        case 72: break;
        case 19: 
          { // on a reconnu le début d'une boucle if
  return creerSymbole("IF",TypeSymboles.IF);
          }
        case 73: break;
        case 34: 
          { // on a reconnu le mot-clé "true"
   return creerSymbole("TRUE",TypeSymboles.TRUE);
          }
        case 74: break;
        case 15: 
          { // on a reconnu un ")"
  return creerSymbole("PARENTF",TypeSymboles.PARENTF);
          }
        case 75: break;
        case 22: 
          { // on a reconnu un ">="
  return creerSymbole("SUPE",TypeSymboles.SUPE);
          }
        case 76: break;
        case 16: 
          { // on a reconnu le mot-clé "or"
   return creerSymbole("OR",TypeSymboles.OR);
          }
        case 77: break;
        case 13: 
          { // on a reconnu un "*"
  return creerSymbole("MULT",TypeSymboles.MULT);
          }
        case 78: break;
        case 33: 
          { // on a reconnu le mot-clé "loop"
  return creerSymbole("LOOP",TypeSymboles.LOOP);
          }
        case 79: break;
        case 21: 
          { // on a reconnu un "<="
  return creerSymbole("INFE",TypeSymboles.INFE);
          }
        case 80: break;
        case 3: 
          { // on a reconnu un identificateur, par la suite il
		  // faudra lui associer par ex son nom : on utilise
		  // yytext() qui représente la portion du texte
		  // d'entrée reconnue 
 return creerSymbole("IDENT",TypeSymboles.IDENT,yytext());
          }
        case 81: break;
        case 12: 
          { // on a reconnu un "+"
  return creerSymbole("PLUS",TypeSymboles.PLUS);
          }
        case 82: break;
        case 42: 
          { // on a recconu le mot-clé writeln
  return creerSymbole("WRITELN",TypeSymboles.WRITELN);
          }
        case 83: break;
        case 32: 
          { // on a reconnu le mot-clé "else"
  return creerSymbole("ELSE",TypeSymboles.ELSE);
          }
        case 84: break;
        case 23: 
          { // on a reconnu un format d'impression d'entier
return creerSymbole("FORIMPINT",TypeSymboles.FORIMPINT);
          }
        case 85: break;
        case 20: 
          { // on a reconnu un "/="
  return creerSymbole("DIFF",TypeSymboles.DIFF);
          }
        case 86: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {   return new Symbole(TypeSymboles.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
