
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 02 16:30:34 CET 2010
//----------------------------------------------------

package ava.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int MULT = 36;
  public static final int FININSTR = 10;
  public static final int EGAL = 27;
  public static final int INFS = 29;
  public static final int ENDLOOP = 23;
  public static final int SUPS = 30;
  public static final int WRITE = 12;
  public static final int UNAIRE = 26;
  public static final int NOT = 42;
  public static final int AND = 41;
  public static final int PARENTO = 24;
  public static final int OR = 40;
  public static final int INFE = 31;
  public static final int DIV = 35;
  public static final int SUPE = 32;
  public static final int PARENTF = 25;
  public static final int LOOP = 22;
  public static final int PLUS = 33;
  public static final int IF = 17;
  public static final int WRITELN = 13;
  public static final int EOF = 0;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int MOINS = 34;
  public static final int MOD = 37;
  public static final int IDENT = 3;
  public static final int DECLBOOL = 7;
  public static final int ENDIF = 20;
  public static final int ELSE = 19;
  public static final int READ = 8;
  public static final int SEPVAR = 11;
  public static final int WHILE = 21;
  public static final int FORIMPSTR = 16;
  public static final int THEN = 18;
  public static final int PROG = 5;
  public static final int DECLINT = 6;
  public static final int FORIMPINT = 14;
  public static final int DIFF = 28;
  public static final int ENTIER = 4;
  public static final int AFF = 9;
  public static final int CHAINE = 2;
  public static final int FALSE = 39;
  public static final int FORIMPBOOL = 15;
}

