
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 16 20:46:52 CET 2010
//----------------------------------------------------

package ava.analyseurs;

/** CUP generated class containing symbol constants. */
public class TypeSymboles {
  /* terminals */
  public static final int SEP = 24;
  public static final int MULT = 21;
  public static final int FININSTR = 23;
  public static final int EGAL = 27;
  public static final int WRITE = 13;
  public static final int UNAIRE = 39;
  public static final int SUPEGAL = 32;
  public static final int NOT = 38;
  public static final int AND = 37;
  public static final int OR = 36;
  public static final int INF = 29;
  public static final int AFFECT = 22;
  public static final int INFEGAL = 31;
  public static final int FI = 5;
  public static final int DIV = 20;
  public static final int FORMATI = 15;
  public static final int LOOP = 10;
  public static final int PLUS = 18;
  public static final int IF = 6;
  public static final int WRITELN = 14;
  public static final int FORMATC = 17;
  public static final int FORMATB = 16;
  public static final int EOF = 0;
  public static final int TRUE = 34;
  public static final int error = 1;
  public static final int MOINS = 19;
  public static final int DONE = 9;
  public static final int MOD = 33;
  public static final int IDENT = 41;
  public static final int DECLBOOL = 4;
  public static final int ELSE = 7;
  public static final int PARO = 25;
  public static final int READ = 12;
  public static final int WHILE = 11;
  public static final int THEN = 8;
  public static final int SUP = 30;
  public static final int PROG = 2;
  public static final int PARF = 26;
  public static final int DECLINT = 3;
  public static final int DIFF = 28;
  public static final int ENTIER = 42;
  public static final int CHAINE = 40;
  public static final int FALSE = 35;
}

